# Generated by Django 5.2.4 on 2025-07-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='number_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
