# Generated by Django 5.2.4 on 2025-07-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpost_number_of_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='number_of_views',
            new_name='views',
        ),
    ]
