# Generated by Django 5.2.4 on 2025-07-15 07:36

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(blank=True, default='blog_pictures/default_image.jpg', upload_to=blogs.models.rename_image),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_user.png', upload_to=blogs.models.rename_profile_picture),
        ),
    ]
