# Generated by Django 5.2.4 on 2025-07-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blogger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.blogger'),
        ),
    ]
