# Generated by Django 5.2.4 on 2025-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blogpost_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
